//! App-facing TypeScript binding generation and JSON integer policy.

use reticulum_appliance_runtime::{
    ApplianceSnapshot, BASIC_LXMF_SELECTION_OVERHEAD_BYTES, BytesEncoding, BytesView,
    ConnectionState, ConnectionTransport, ContactRequest, ContactView, ConversationPeerView,
    DeviceView, DiagnosticInterfaceKindView, DiagnosticInterfaceStateView, DiagnosticInterfaceView,
    DiagnosticLoraDataTxEvidenceView, DiagnosticLoraLastRxView, DiagnosticLoraLastTxView,
    DiagnosticLoraTxFamilyView, DiagnosticLoraTxOutcomeView, EMPTY_LXMF_FIELDS_ENCODED_BYTES,
    LINK_PACKET_MAX_CONTENT, LoraDiagnosticsView, LoraRadioProfileView, MAX_CONTACT_NAME_BYTES,
    MAX_ENCODED_SIDEBAND_LOCATION_FIELDS_BYTES, ManualServiceAnnounceDisposition,
    MessageActivityEventView, MessageActivityKindView, MessageActivityPageRequest,
    MessageActivityPageView, MessageIngressObservationView, MessageLocationView,
    MessageSignalObservationView, MutationOutcome, MutationResponse, NearbyPeerView,
    NetworkConfigMutation, NetworkConfigMutationOutcome, NetworkConfigMutationRequest,
    NetworkConfigView, NetworkRuntimeStatusView, NomadFetchFailure, NomadFetchPhase,
    NomadFetchPollRequest, NomadFetchPollResponse, NomadFetchStartOutcome, NomadFetchStartRequest,
    NomadFetchStartResponse, PacketEvidenceView, PhoneLocationAuthorizationView,
    PhoneLocationObservationView, PhoneLocationSourceView, PhoneLocationUnavailableReasonView,
    RadioRoutesStatusView, RadioTraceAttemptOutcomeView, RadioTraceEventKindView,
    RadioTraceEventView, RadioTraceMessageCorrelationView, RadioTracePageRequest,
    RadioTracePageView, RadioTraceProfileView, RadioTraceRouteResolutionView,
    RadioTraceTxOutcomeView, RetainedRouteView, ReticulumDnsDiagnosticsView,
    ReticulumDnsPrimaryOutcomeView, ReticulumDnsRawAttemptView, ReticulumDnsRawOutcomeView,
    ReticulumDnsRawSetupStateView, ReticulumDnsRawSourceView, ReticulumDnsResolutionSourceView,
    ReticulumDnsResolutionView, ReticulumProbeFailure, ReticulumProbeIngressView,
    ReticulumProbePhase, ReticulumProbePollRequest, ReticulumProbePollResponse,
    ReticulumProbeSignalView, ReticulumProbeStartOutcome, ReticulumProbeStartRequest,
    ReticulumProbeStartResponse, ReticulumProbeSuccessView, ReticulumTcpFailureView,
    ReticulumTcpPeerHostnameInput, ReticulumTcpPeerIpv4Input, ReticulumTcpPeerStateView,
    ReticulumTcpPeerView, RetrySendOutcome, RetrySendRequest, RetrySendResponse, RmapPhoneLocation,
    RnsDiagnosticsView, RouteDiagnosticResolutionView, SendOutcome, SendRequest, SendResponse,
    TimelineDirection, TimelineStatus, TimelineView, WifiCredentialUpdate, WifiNetworkProfileView,
    WifiStationStateView,
};
use reticulum_device_api::{
    API_VERSION_MAJOR, API_VERSION_MINOR, DEFAULT_RETICULUM_TCP_PORT, MAX_LXMF_BASIC_CONTENT_BYTES,
    MAX_LXMF_BASIC_TITLE_BYTES, MAX_LXMF_READ_CHUNK_BYTES, MAX_MESSAGE_BYTES, MAX_NOMAD_PAGE_BYTES,
    MAX_NOMAD_PAGE_PATH_BYTES, MAX_NOMAD_REQUEST_TIMESTAMP_UNIX_MS,
    MAX_RETICULUM_TCP_PEER_HOSTNAME_BYTES, MAX_WIFI_NETWORK_PROFILES, MAX_WIFI_PASSPHRASE_BYTES,
    MAX_WIFI_SSID_BYTES, MIN_WIFI_PASSPHRASE_BYTES,
};
use ts_rs::TS;

use crate::onboarding::{
    OnboardingFault, OnboardingMethod, OnboardingSnapshot, OnboardingStage, OnboardingState,
    OnboardingView, RecoveryAction, RecoveryRequest,
};
use crate::web::{ErrorBody, HttpApplianceSnapshot, HttpConnectionState, SessionRequest};

pub(crate) use reticulum_appliance_runtime::{JsonSafeInteger, serialize_json_safe_u64};

/// Marker for successful HTTP responses that deliberately contain no body.
#[derive(TS)]
#[ts(type = "undefined")]
pub struct NoContent;

/// Return the deterministic TypeScript module generated from the Rust wire DTOs.
#[must_use]
pub fn render_api_bindings() -> String {
    let config = ts_rs::Config::new().with_large_int("JsonSafeInteger");
    let mut output = String::from(
        "// @generated by reticulum-appliance-service; DO NOT EDIT.\n\
         // Run `cargo run --locked -p reticulum-appliance-service --bin export-api-bindings`.\n\
         //\n\
         // Every JsonSafeInteger is encoded as a JSON number in the inclusive range\n\
         // 0..=Number.MAX_SAFE_INTEGER. Rust validates this contract at the wire boundary.\n\n",
    );

    output.push_str(&format!(
        "export const DEVICE_API_VERSION_MAJOR = {API_VERSION_MAJOR} as const;\n\
         export const DEVICE_API_VERSION_MINOR = {API_VERSION_MINOR} as const;\n\
         export const MAX_MESSAGE_BYTES = {MAX_MESSAGE_BYTES} as const;\n\
         export const MAX_LXMF_READ_CHUNK_BYTES = {MAX_LXMF_READ_CHUNK_BYTES} as const;\n\
         export const MAX_CONTACT_NAME_BYTES = {MAX_CONTACT_NAME_BYTES} as const;\n\
         export const MAX_LXMF_BASIC_TITLE_BYTES = {MAX_LXMF_BASIC_TITLE_BYTES} as const;\n\
         export const MAX_LXMF_BASIC_CONTENT_BYTES = {MAX_LXMF_BASIC_CONTENT_BYTES} as const;\n\
         export const MAX_LXMF_DIRECT_CONTENT_BYTES = {LINK_PACKET_MAX_CONTENT} as const;\n\
         export const BASIC_LXMF_SELECTION_OVERHEAD_BYTES = {BASIC_LXMF_SELECTION_OVERHEAD_BYTES} as const;\n\
         export const EMPTY_LXMF_FIELDS_ENCODED_BYTES = {EMPTY_LXMF_FIELDS_ENCODED_BYTES} as const;\n\
         export const MAX_ENCODED_SIDEBAND_LOCATION_FIELDS_BYTES = {MAX_ENCODED_SIDEBAND_LOCATION_FIELDS_BYTES} as const;\n\
         export const MAX_NOMAD_PAGE_PATH_BYTES = {MAX_NOMAD_PAGE_PATH_BYTES} as const;\n\
         export const MAX_NOMAD_PAGE_BYTES = {MAX_NOMAD_PAGE_BYTES} as const;\n\
         export const MAX_NOMAD_REQUEST_TIMESTAMP_UNIX_MS = {MAX_NOMAD_REQUEST_TIMESTAMP_UNIX_MS} as const;\n\
         export const MAX_WIFI_NETWORK_PROFILES = {MAX_WIFI_NETWORK_PROFILES} as const;\n\
         export const MAX_WIFI_SSID_BYTES = {MAX_WIFI_SSID_BYTES} as const;\n\
         export const MIN_WIFI_PASSPHRASE_BYTES = {MIN_WIFI_PASSPHRASE_BYTES} as const;\n\
         export const MAX_WIFI_PASSPHRASE_BYTES = {MAX_WIFI_PASSPHRASE_BYTES} as const;\n\
         export const MAX_RETICULUM_TCP_PEER_HOSTNAME_BYTES = {MAX_RETICULUM_TCP_PEER_HOSTNAME_BYTES} as const;\n\
         export const DEFAULT_RETICULUM_TCP_PORT = {DEFAULT_RETICULUM_TCP_PORT} as const;\n\n"
    ));

    append_declaration::<JsonSafeInteger>(&mut output, &config);
    append_declaration::<NoContent>(&mut output, &config);
    append_declaration::<ConnectionTransport>(&mut output, &config);
    append_declaration::<ConnectionState>(&mut output, &config);
    append_declaration::<DeviceView>(&mut output, &config);
    append_declaration::<ApplianceSnapshot>(&mut output, &config);
    append_declaration::<HttpConnectionState>(&mut output, &config);
    append_declaration::<HttpApplianceSnapshot>(&mut output, &config);
    append_declaration::<OnboardingStage>(&mut output, &config);
    append_declaration::<OnboardingFault>(&mut output, &config);
    append_declaration::<OnboardingState>(&mut output, &config);
    append_declaration::<OnboardingSnapshot>(&mut output, &config);
    append_declaration::<OnboardingMethod>(&mut output, &config);
    append_declaration::<OnboardingView>(&mut output, &config);
    append_declaration::<ContactView>(&mut output, &config);
    append_declaration::<ConversationPeerView>(&mut output, &config);
    append_declaration::<NearbyPeerView>(&mut output, &config);
    append_declaration::<DiagnosticInterfaceKindView>(&mut output, &config);
    append_declaration::<DiagnosticInterfaceStateView>(&mut output, &config);
    append_declaration::<DiagnosticInterfaceView>(&mut output, &config);
    append_declaration::<DiagnosticLoraTxOutcomeView>(&mut output, &config);
    append_declaration::<DiagnosticLoraTxFamilyView>(&mut output, &config);
    append_declaration::<DiagnosticLoraDataTxEvidenceView>(&mut output, &config);
    append_declaration::<DiagnosticLoraLastRxView>(&mut output, &config);
    append_declaration::<DiagnosticLoraLastTxView>(&mut output, &config);
    append_declaration::<LoraDiagnosticsView>(&mut output, &config);
    append_declaration::<RnsDiagnosticsView>(&mut output, &config);
    append_declaration::<RouteDiagnosticResolutionView>(&mut output, &config);
    append_declaration::<RetainedRouteView>(&mut output, &config);
    append_declaration::<RadioRoutesStatusView>(&mut output, &config);
    append_declaration::<BytesEncoding>(&mut output, &config);
    append_declaration::<BytesView>(&mut output, &config);
    append_declaration::<WifiNetworkProfileView>(&mut output, &config);
    append_declaration::<ReticulumTcpPeerView>(&mut output, &config);
    append_declaration::<RmapPhoneLocation>(&mut output, &config);
    append_declaration::<LoraRadioProfileView>(&mut output, &config);
    append_declaration::<NetworkConfigView>(&mut output, &config);
    append_declaration::<WifiStationStateView>(&mut output, &config);
    append_declaration::<ReticulumTcpPeerStateView>(&mut output, &config);
    append_declaration::<ReticulumTcpFailureView>(&mut output, &config);
    append_declaration::<ReticulumDnsPrimaryOutcomeView>(&mut output, &config);
    append_declaration::<ReticulumDnsRawSetupStateView>(&mut output, &config);
    append_declaration::<ReticulumDnsRawSourceView>(&mut output, &config);
    append_declaration::<ReticulumDnsRawOutcomeView>(&mut output, &config);
    append_declaration::<ReticulumDnsRawAttemptView>(&mut output, &config);
    append_declaration::<ReticulumDnsResolutionSourceView>(&mut output, &config);
    append_declaration::<ReticulumDnsResolutionView>(&mut output, &config);
    append_declaration::<ReticulumDnsDiagnosticsView>(&mut output, &config);
    append_declaration::<NetworkRuntimeStatusView>(&mut output, &config);
    append_declaration::<WifiCredentialUpdate>(&mut output, &config);
    append_declaration::<ReticulumTcpPeerIpv4Input>(&mut output, &config);
    append_declaration::<ReticulumTcpPeerHostnameInput>(&mut output, &config);
    append_declaration::<NetworkConfigMutation>(&mut output, &config);
    append_declaration::<NetworkConfigMutationRequest>(&mut output, &config);
    append_declaration::<NetworkConfigMutationOutcome>(&mut output, &config);
    append_declaration::<ManualServiceAnnounceDisposition>(&mut output, &config);
    append_declaration::<TimelineDirection>(&mut output, &config);
    append_declaration::<TimelineStatus>(&mut output, &config);
    append_declaration::<PacketEvidenceView>(&mut output, &config);
    append_declaration::<MessageSignalObservationView>(&mut output, &config);
    append_declaration::<MessageIngressObservationView>(&mut output, &config);
    append_declaration::<MessageLocationView>(&mut output, &config);
    append_declaration::<TimelineView>(&mut output, &config);
    append_declaration::<MessageActivityKindView>(&mut output, &config);
    append_declaration::<PhoneLocationAuthorizationView>(&mut output, &config);
    append_declaration::<PhoneLocationSourceView>(&mut output, &config);
    append_declaration::<PhoneLocationUnavailableReasonView>(&mut output, &config);
    append_declaration::<PhoneLocationObservationView>(&mut output, &config);
    append_declaration::<MessageActivityEventView>(&mut output, &config);
    append_declaration::<MessageActivityPageRequest>(&mut output, &config);
    append_declaration::<MessageActivityPageView>(&mut output, &config);
    append_declaration::<RadioTraceProfileView>(&mut output, &config);
    append_declaration::<RadioTraceRouteResolutionView>(&mut output, &config);
    append_declaration::<RadioTraceTxOutcomeView>(&mut output, &config);
    append_declaration::<RadioTraceAttemptOutcomeView>(&mut output, &config);
    append_declaration::<RadioTraceEventKindView>(&mut output, &config);
    append_declaration::<RadioTraceMessageCorrelationView>(&mut output, &config);
    append_declaration::<RadioTraceEventView>(&mut output, &config);
    append_declaration::<RadioTracePageRequest>(&mut output, &config);
    append_declaration::<RadioTracePageView>(&mut output, &config);
    append_declaration::<SessionRequest>(&mut output, &config);
    append_declaration::<RecoveryAction>(&mut output, &config);
    append_declaration::<RecoveryRequest>(&mut output, &config);
    append_declaration::<ContactRequest>(&mut output, &config);
    append_declaration::<MutationOutcome>(&mut output, &config);
    append_declaration::<MutationResponse>(&mut output, &config);
    append_declaration::<SendRequest>(&mut output, &config);
    append_declaration::<SendOutcome>(&mut output, &config);
    append_declaration::<SendResponse>(&mut output, &config);
    append_declaration::<RetrySendRequest>(&mut output, &config);
    append_declaration::<RetrySendOutcome>(&mut output, &config);
    append_declaration::<RetrySendResponse>(&mut output, &config);
    append_declaration::<NomadFetchStartRequest>(&mut output, &config);
    append_declaration::<NomadFetchPollRequest>(&mut output, &config);
    append_declaration::<NomadFetchStartOutcome>(&mut output, &config);
    append_declaration::<NomadFetchStartResponse>(&mut output, &config);
    append_declaration::<NomadFetchPhase>(&mut output, &config);
    append_declaration::<NomadFetchFailure>(&mut output, &config);
    append_declaration::<NomadFetchPollResponse>(&mut output, &config);
    append_declaration::<ReticulumProbeStartRequest>(&mut output, &config);
    append_declaration::<ReticulumProbePollRequest>(&mut output, &config);
    append_declaration::<ReticulumProbeStartOutcome>(&mut output, &config);
    append_declaration::<ReticulumProbeStartResponse>(&mut output, &config);
    append_declaration::<ReticulumProbePhase>(&mut output, &config);
    append_declaration::<ReticulumProbeFailure>(&mut output, &config);
    append_declaration::<ReticulumProbeSignalView>(&mut output, &config);
    append_declaration::<ReticulumProbeIngressView>(&mut output, &config);
    append_declaration::<ReticulumProbeSuccessView>(&mut output, &config);
    append_declaration::<ReticulumProbePollResponse>(&mut output, &config);
    append_declaration::<ErrorBody>(&mut output, &config);
    normalize_generated_module(output)
}

fn append_declaration<T: TS>(output: &mut String, config: &ts_rs::Config) {
    if let Some(docs) = T::docs() {
        output.push_str(&docs);
    }
    output.push_str("export ");
    output.push_str(&T::decl(config));
    output.push_str("\n\n");
}

fn normalize_generated_module(output: String) -> String {
    let mut normalized = String::with_capacity(output.len());
    for line in output.lines() {
        normalized.push_str(line.trim_end());
        normalized.push('\n');
    }
    while normalized.ends_with("\n\n") {
        normalized.pop();
    }
    normalized
}

#[cfg(test)]
mod tests {
    use reticulum_appliance_runtime::{MAX_JSON_SAFE_INTEGER, deserialize_json_safe_u64};
    use serde::{Deserialize, Serialize};

    use super::*;

    #[derive(Serialize)]
    struct SafeOutput {
        #[serde(serialize_with = "serialize_json_safe_u64")]
        value: u64,
    }

    #[derive(Deserialize)]
    struct SafeInput {
        #[serde(deserialize_with = "deserialize_json_safe_u64")]
        value: u64,
    }

    #[test]
    fn safe_integer_contract_accepts_its_edges_and_rejects_larger_values() {
        assert_eq!(
            serde_json::to_string(&SafeOutput {
                value: MAX_JSON_SAFE_INTEGER,
            })
            .unwrap(),
            format!(r#"{{"value":{MAX_JSON_SAFE_INTEGER}}}"#)
        );
        assert!(
            serde_json::to_string(&SafeOutput {
                value: MAX_JSON_SAFE_INTEGER + 1,
            })
            .is_err()
        );
        assert_eq!(
            serde_json::from_str::<SafeInput>(&format!(r#"{{"value":{MAX_JSON_SAFE_INTEGER}}}"#))
                .unwrap()
                .value,
            MAX_JSON_SAFE_INTEGER
        );
        assert!(
            serde_json::from_str::<SafeInput>(&format!(
                r#"{{"value":{}}}"#,
                MAX_JSON_SAFE_INTEGER + 1
            ))
            .is_err()
        );
    }

    #[test]
    fn network_bindings_are_generated_from_the_secret_safe_runtime_contract() {
        let bindings = render_api_bindings();
        assert!(bindings.contains("export type NetworkConfigView ="));
        assert!(bindings.contains("export type NetworkConfigMutationRequest ="));
        assert!(bindings.contains("export type NetworkConfigMutationOutcome ="));
        assert!(bindings.contains("\"kind\": \"replace\""));
        assert!(bindings.contains("passphrase: string"));
        assert!(bindings.contains("hostname: string"));
        assert!(bindings.contains("\"kind\": \"set_gateway_policy\""));
        assert!(bindings.contains("\"kind\": \"set_rmap_config\""));
        assert!(bindings.contains("export type ManualServiceAnnounceDisposition ="));
        assert!(bindings.contains("export type ReticulumTcpFailureView ="));
        assert!(bindings.contains("\"backoff\""));
        assert!(bindings.contains("\"dns_timeout\""));
        assert!(bindings.contains("export type ReticulumDnsDiagnosticsView ="));
        assert!(bindings.contains("\"kind\": \"response_code\""));
        assert!(bindings.contains("dns_diagnostics: ReticulumDnsDiagnosticsView | null"));
        assert!(bindings.contains("\"outcome\": \"revision_conflict\""));
        assert!(bindings.contains("export const DEFAULT_RETICULUM_TCP_PORT = 4242 as const;"));
    }

    #[test]
    fn radio_and_route_bindings_preserve_local_diagnostics_semantics() {
        let bindings = render_api_bindings();
        assert!(bindings.contains("export type RadioRoutesStatusView ="));
        assert!(bindings.contains("export type RetainedRouteView ="));
        assert!(bindings.contains("last_local_use_age_ms: JsonSafeInteger | null"));
        assert!(bindings.contains("route_table_revision: JsonSafeInteger"));
        assert!(bindings.contains("\"broadcast_ready\""));
        assert!(bindings.contains("applied_tx_power_dbm: number"));
        assert!(bindings.contains("rssi_dbm: number"));
    }

    #[test]
    fn activity_bindings_preserve_paging_and_lifecycle_semantics() {
        let bindings = render_api_bindings();
        assert!(bindings.contains("export type MessageSignalObservationView ="));
        assert!(bindings.contains("export type MessageIngressObservationView ="));
        assert!(bindings.contains("interface_id: number"));
        assert!(bindings.contains("signal: MessageSignalObservationView | null"));
        assert!(bindings.contains("ingress_observation: MessageIngressObservationView | null"));
        assert!(bindings.contains("export type MessageActivityPageRequest ="));
        assert!(bindings.contains("before_event_id: JsonSafeInteger | null"));
        assert!(bindings.contains("timeline_sequence: JsonSafeInteger | null"));
        assert!(bindings.contains("export type MessageActivityPageView ="));
        assert!(bindings.contains("export type PhoneLocationObservationView ="));
        assert!(bindings.contains("\"state\": \"available\""));
        assert!(bindings.contains("captured_at_unix_ms: JsonSafeInteger"));
        assert!(bindings.contains("export type MessageActivityEventView ="));
        assert!(bindings.contains("attempt_location: PhoneLocationObservationView | null"));
        assert!(bindings.contains("ingress_observation: MessageIngressObservationView | null"));
        assert!(bindings.contains("export type MessageActivityKindView ="));
        assert!(bindings.contains("\"kind\": \"outbound_status\""));
        assert!(bindings.contains("packet_evidence: PacketEvidenceView | null"));
        assert!(bindings.contains("\"outbound_requeued\""));
    }

    #[test]
    fn probe_bindings_preserve_receiver_local_return_hop_semantics() {
        let bindings = render_api_bindings();
        assert!(bindings.contains("export type ReticulumProbeStartRequest ="));
        assert!(bindings.contains("export type ReticulumProbePollResponse ="));
        assert!(bindings.contains("\"state\": \"succeeded\""));
        assert!(bindings.contains("round_trip_ms: number"));
        assert!(bindings.contains("ingress_observation: ReticulumProbeIngressView"));
        assert!(bindings.contains("signal: ReticulumProbeSignalView | null"));
    }

    #[test]
    fn committed_typescript_bindings_match_the_rust_wire_types() {
        let committed = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../clients/appliance/src/generated/api.ts"
        ));
        assert_eq!(committed, render_api_bindings());
    }
}
