// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "reticulum-appliance-native.h"

extern "C" void reticulum_appliance_prns_android_link_anchor();

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_org_reticulum_appliance_nativebridge_ApplianceNativeModule and reticulum_appliancenative
// by comparing the whole line here.
/*
Java_org_reticulum_appliance_nativebridge_ApplianceNativeModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return reticulum_appliancenative::multiply(a, b);
}
*/

// Installer coming from ApplianceNativeModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_org_reticulum_appliance_nativebridge_ApplianceNativeModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    reticulum_appliance_prns_android_link_anchor();
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return reticulum_appliancenative::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_org_reticulum_appliance_nativebridge_ApplianceNativeModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return reticulum_appliancenative::cleanupRustCrate(*runtime);
}