//! App-facing TypeScript binding generation and JSON integer policy.

use reticulum_device_api::{
    API_VERSION_MAJOR, API_VERSION_MINOR, MAX_LXMF_BASIC_CONTENT_BYTES, MAX_LXMF_BASIC_TITLE_BYTES,
    MAX_LXMF_READ_CHUNK_BYTES, MAX_MESSAGE_BYTES,
};
use reticulum_lxmf_chat_runtime::{
    ApplianceSnapshot, BytesEncoding, BytesView, ConnectionState, ConnectionTransport,
    ContactRequest, ContactView, DeviceView, MAX_CONTACT_NAME_BYTES, MutationOutcome,
    MutationResponse, SendOutcome, SendRequest, SendResponse, TimelineDirection, TimelineStatus,
    TimelineView,
};
use ts_rs::TS;

use crate::onboarding::{OnboardingFault, OnboardingSnapshot, OnboardingStage, OnboardingState};
use crate::web::{
    ErrorBody, HttpApplianceSnapshot, HttpConnectionState, OnboardingMethod, OnboardingView,
    RecoveryAction, RecoveryRequest, SessionRequest,
};

pub(crate) use reticulum_lxmf_chat_runtime::{JsonSafeInteger, serialize_json_safe_u64};

/// Marker for successful HTTP responses that deliberately contain no body.
#[derive(TS)]
#[ts(type = "undefined")]
pub struct NoContent;

/// Return the deterministic TypeScript module generated from the Rust wire DTOs.
#[must_use]
pub fn render_api_bindings() -> String {
    let config = ts_rs::Config::new().with_large_int("JsonSafeInteger");
    let mut output = String::from(
        "// @generated by reticulum-lxmf-chat-service; DO NOT EDIT.\n\
         // Run `cargo run --locked -p reticulum-lxmf-chat-service --bin export-api-bindings`.\n\
         //\n\
         // Every JsonSafeInteger is encoded as a JSON number in the inclusive range\n\
         // 0..=Number.MAX_SAFE_INTEGER. Rust validates this contract at the wire boundary.\n\n",
    );

    output.push_str(&format!(
        "export const DEVICE_API_VERSION_MAJOR = {API_VERSION_MAJOR} as const;\n\
         export const DEVICE_API_VERSION_MINOR = {API_VERSION_MINOR} as const;\n\
         export const MAX_MESSAGE_BYTES = {MAX_MESSAGE_BYTES} as const;\n\
         export const MAX_LXMF_READ_CHUNK_BYTES = {MAX_LXMF_READ_CHUNK_BYTES} as const;\n\
         export const MAX_CONTACT_NAME_BYTES = {MAX_CONTACT_NAME_BYTES} as const;\n\
         export const MAX_LXMF_BASIC_TITLE_BYTES = {MAX_LXMF_BASIC_TITLE_BYTES} as const;\n\
         export const MAX_LXMF_BASIC_CONTENT_BYTES = {MAX_LXMF_BASIC_CONTENT_BYTES} as const;\n\n"
    ));

    append_declaration::<JsonSafeInteger>(&mut output, &config);
    append_declaration::<NoContent>(&mut output, &config);
    append_declaration::<ConnectionTransport>(&mut output, &config);
    append_declaration::<ConnectionState>(&mut output, &config);
    append_declaration::<DeviceView>(&mut output, &config);
    append_declaration::<ApplianceSnapshot>(&mut output, &config);
    append_declaration::<HttpConnectionState>(&mut output, &config);
    append_declaration::<HttpApplianceSnapshot>(&mut output, &config);
    append_declaration::<OnboardingStage>(&mut output, &config);
    append_declaration::<OnboardingFault>(&mut output, &config);
    append_declaration::<OnboardingState>(&mut output, &config);
    append_declaration::<OnboardingSnapshot>(&mut output, &config);
    append_declaration::<OnboardingMethod>(&mut output, &config);
    append_declaration::<OnboardingView>(&mut output, &config);
    append_declaration::<ContactView>(&mut output, &config);
    append_declaration::<BytesEncoding>(&mut output, &config);
    append_declaration::<BytesView>(&mut output, &config);
    append_declaration::<TimelineDirection>(&mut output, &config);
    append_declaration::<TimelineStatus>(&mut output, &config);
    append_declaration::<TimelineView>(&mut output, &config);
    append_declaration::<SessionRequest>(&mut output, &config);
    append_declaration::<RecoveryAction>(&mut output, &config);
    append_declaration::<RecoveryRequest>(&mut output, &config);
    append_declaration::<ContactRequest>(&mut output, &config);
    append_declaration::<MutationOutcome>(&mut output, &config);
    append_declaration::<MutationResponse>(&mut output, &config);
    append_declaration::<SendRequest>(&mut output, &config);
    append_declaration::<SendOutcome>(&mut output, &config);
    append_declaration::<SendResponse>(&mut output, &config);
    append_declaration::<ErrorBody>(&mut output, &config);
    normalize_generated_module(output)
}

fn append_declaration<T: TS>(output: &mut String, config: &ts_rs::Config) {
    if let Some(docs) = T::docs() {
        output.push_str(&docs);
    }
    output.push_str("export ");
    output.push_str(&T::decl(config));
    output.push_str("\n\n");
}

fn normalize_generated_module(output: String) -> String {
    let mut normalized = String::with_capacity(output.len());
    for line in output.lines() {
        normalized.push_str(line.trim_end());
        normalized.push('\n');
    }
    while normalized.ends_with("\n\n") {
        normalized.pop();
    }
    normalized
}

#[cfg(test)]
mod tests {
    use reticulum_lxmf_chat_runtime::{MAX_JSON_SAFE_INTEGER, deserialize_json_safe_u64};
    use serde::{Deserialize, Serialize};

    use super::*;

    #[derive(Serialize)]
    struct SafeOutput {
        #[serde(serialize_with = "serialize_json_safe_u64")]
        value: u64,
    }

    #[derive(Deserialize)]
    struct SafeInput {
        #[serde(deserialize_with = "deserialize_json_safe_u64")]
        value: u64,
    }

    #[test]
    fn safe_integer_contract_accepts_its_edges_and_rejects_larger_values() {
        assert_eq!(
            serde_json::to_string(&SafeOutput {
                value: MAX_JSON_SAFE_INTEGER,
            })
            .unwrap(),
            format!(r#"{{"value":{MAX_JSON_SAFE_INTEGER}}}"#)
        );
        assert!(
            serde_json::to_string(&SafeOutput {
                value: MAX_JSON_SAFE_INTEGER + 1,
            })
            .is_err()
        );
        assert_eq!(
            serde_json::from_str::<SafeInput>(&format!(r#"{{"value":{MAX_JSON_SAFE_INTEGER}}}"#))
                .unwrap()
                .value,
            MAX_JSON_SAFE_INTEGER
        );
        assert!(
            serde_json::from_str::<SafeInput>(&format!(
                r#"{{"value":{}}}"#,
                MAX_JSON_SAFE_INTEGER + 1
            ))
            .is_err()
        );
    }

    #[test]
    fn committed_typescript_bindings_match_the_rust_wire_types() {
        let committed = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../clients/appliance/src/generated/api.ts"
        ));
        assert_eq!(committed, render_api_bindings());
    }
}
