//! App-facing TypeScript binding generation and JSON integer policy.

use reticulum_device_api::{MAX_LXMF_BASIC_CONTENT_BYTES, MAX_LXMF_BASIC_TITLE_BYTES};
use serde::de::Error as _;
use serde::{Deserialize, Deserializer, Serializer};
use ts_rs::TS;

use crate::onboarding::{OnboardingFault, OnboardingSnapshot, OnboardingStage, OnboardingState};
use crate::runtime::{
    ApplianceSnapshot, BytesEncoding, BytesView, ConnectionState, ContactView, DeviceView,
    TimelineDirection, TimelineStatus, TimelineView,
};
use crate::web::{
    ContactRequest, ErrorBody, MAX_CONTACT_NAME_BYTES, MutationOutcome, MutationResponse,
    OnboardingView, RecoveryAction, RecoveryRequest, SendOutcome, SendRequest, SendResponse,
    SessionRequest,
};

/// Largest integer JSON clients may represent without precision loss.
pub const MAX_JSON_SAFE_INTEGER: u64 = 9_007_199_254_740_991;

/// A JSON number constrained to JavaScript's lossless integer range.
#[derive(TS)]
#[ts(type = "number")]
pub struct JsonSafeInteger;

/// Marker for successful HTTP responses that deliberately contain no body.
#[derive(TS)]
#[ts(type = "undefined")]
pub struct NoContent;

pub(crate) fn serialize_json_safe_u64<S>(value: &u64, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    if *value > MAX_JSON_SAFE_INTEGER {
        return Err(serde::ser::Error::custom(
            "integer exceeds the JSON safe-integer contract",
        ));
    }
    serializer.serialize_u64(*value)
}

pub(crate) fn serialize_optional_json_safe_u64<S>(
    value: &Option<u64>,
    serializer: S,
) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    match value {
        Some(value) => serialize_json_safe_u64(value, serializer),
        None => serializer.serialize_none(),
    }
}

pub(crate) fn serialize_json_safe_usize<S>(value: &usize, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    let value = u64::try_from(*value)
        .map_err(|_| serde::ser::Error::custom("integer exceeds the JSON u64 range"))?;
    serialize_json_safe_u64(&value, serializer)
}

pub(crate) fn deserialize_json_safe_u64<'de, D>(deserializer: D) -> Result<u64, D::Error>
where
    D: Deserializer<'de>,
{
    let value = u64::deserialize(deserializer)?;
    if value > MAX_JSON_SAFE_INTEGER {
        return Err(D::Error::custom(
            "integer exceeds the JSON safe-integer contract",
        ));
    }
    Ok(value)
}

/// Return the deterministic TypeScript module generated from the Rust wire DTOs.
#[must_use]
pub fn render_api_bindings() -> String {
    let config = ts_rs::Config::new().with_large_int("JsonSafeInteger");
    let mut output = String::from(
        "// @generated by reticulum-lxmf-chat-service; DO NOT EDIT.\n\
         // Run `cargo run --locked -p reticulum-lxmf-chat-service --bin export-api-bindings`.\n\
         //\n\
         // Every JsonSafeInteger is encoded as a JSON number in the inclusive range\n\
         // 0..=Number.MAX_SAFE_INTEGER. Rust validates this contract at the wire boundary.\n\n",
    );

    output.push_str(&format!(
        "export const MAX_CONTACT_NAME_BYTES = {MAX_CONTACT_NAME_BYTES} as const;\n\
         export const MAX_LXMF_BASIC_TITLE_BYTES = {MAX_LXMF_BASIC_TITLE_BYTES} as const;\n\
         export const MAX_LXMF_BASIC_CONTENT_BYTES = {MAX_LXMF_BASIC_CONTENT_BYTES} as const;\n\n"
    ));

    append_declaration::<JsonSafeInteger>(&mut output, &config);
    append_declaration::<NoContent>(&mut output, &config);
    append_declaration::<ConnectionState>(&mut output, &config);
    append_declaration::<DeviceView>(&mut output, &config);
    append_declaration::<ApplianceSnapshot>(&mut output, &config);
    append_declaration::<OnboardingStage>(&mut output, &config);
    append_declaration::<OnboardingFault>(&mut output, &config);
    append_declaration::<OnboardingState>(&mut output, &config);
    append_declaration::<OnboardingSnapshot>(&mut output, &config);
    append_declaration::<OnboardingView>(&mut output, &config);
    append_declaration::<ContactView>(&mut output, &config);
    append_declaration::<BytesEncoding>(&mut output, &config);
    append_declaration::<BytesView>(&mut output, &config);
    append_declaration::<TimelineDirection>(&mut output, &config);
    append_declaration::<TimelineStatus>(&mut output, &config);
    append_declaration::<TimelineView>(&mut output, &config);
    append_declaration::<SessionRequest>(&mut output, &config);
    append_declaration::<RecoveryAction>(&mut output, &config);
    append_declaration::<RecoveryRequest>(&mut output, &config);
    append_declaration::<ContactRequest>(&mut output, &config);
    append_declaration::<MutationOutcome>(&mut output, &config);
    append_declaration::<MutationResponse>(&mut output, &config);
    append_declaration::<SendRequest>(&mut output, &config);
    append_declaration::<SendOutcome>(&mut output, &config);
    append_declaration::<SendResponse>(&mut output, &config);
    append_declaration::<ErrorBody>(&mut output, &config);
    normalize_generated_module(output)
}

fn append_declaration<T: TS>(output: &mut String, config: &ts_rs::Config) {
    if let Some(docs) = T::docs() {
        output.push_str(&docs);
    }
    output.push_str("export ");
    output.push_str(&T::decl(config));
    output.push_str("\n\n");
}

fn normalize_generated_module(output: String) -> String {
    let mut normalized = String::with_capacity(output.len());
    for line in output.lines() {
        normalized.push_str(line.trim_end());
        normalized.push('\n');
    }
    while normalized.ends_with("\n\n") {
        normalized.pop();
    }
    normalized
}

#[cfg(test)]
mod tests {
    use serde::{Deserialize, Serialize};

    use super::*;

    #[derive(Serialize)]
    struct SafeOutput {
        #[serde(serialize_with = "serialize_json_safe_u64")]
        value: u64,
    }

    #[derive(Deserialize)]
    struct SafeInput {
        #[serde(deserialize_with = "deserialize_json_safe_u64")]
        value: u64,
    }

    #[test]
    fn safe_integer_contract_accepts_its_edges_and_rejects_larger_values() {
        assert_eq!(
            serde_json::to_string(&SafeOutput {
                value: MAX_JSON_SAFE_INTEGER,
            })
            .unwrap(),
            format!(r#"{{"value":{MAX_JSON_SAFE_INTEGER}}}"#)
        );
        assert!(
            serde_json::to_string(&SafeOutput {
                value: MAX_JSON_SAFE_INTEGER + 1,
            })
            .is_err()
        );
        assert_eq!(
            serde_json::from_str::<SafeInput>(&format!(r#"{{"value":{MAX_JSON_SAFE_INTEGER}}}"#))
                .unwrap()
                .value,
            MAX_JSON_SAFE_INTEGER
        );
        assert!(
            serde_json::from_str::<SafeInput>(&format!(
                r#"{{"value":{}}}"#,
                MAX_JSON_SAFE_INTEGER + 1
            ))
            .is_err()
        );
    }

    #[test]
    fn committed_typescript_bindings_match_the_rust_wire_types() {
        let committed = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../clients/appliance/src/generated/api.ts"
        ));
        assert_eq!(committed, render_api_bindings());
    }
}
