import { Platform, StyleSheet } from "react-native";

import { applianceScreenColors as colors } from "./appliance-screen-theme.ts";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, minHeight: "100%", backgroundColor: colors.background },
  keyboardAvoiding: { flex: 1, minHeight: 0 },
  connectivityLoading: {
    flex: 1,
    minHeight: 0,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  activityScroller: { flex: 1, minHeight: 0 },
  activityContent: {
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    gap: 14,
    padding: 18,
    paddingBottom: 44,
  },
  topbar: {
    minHeight: 84,
    paddingHorizontal: 28,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    backgroundColor: "#101411f2",
  },
  topbarCompact: {
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexWrap: "nowrap",
    gap: 8,
  },
  brandCluster: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 18 },
  brandClusterCompact: {
    flex: 1,
    minWidth: 0,
    justifyContent: "space-between",
    flexWrap: "nowrap",
    gap: 8,
  },
  mobileBrand: { color: colors.text, fontSize: 14, fontWeight: "800" },
  mobileContactsButton: {
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: 10,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.panel,
  },
  mobileContactsButtonText: { color: colors.text, fontSize: 12, fontWeight: "700" },
  eyebrow: {
    marginBottom: 3,
    color: colors.green,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2,
  },
  title: { color: colors.text, fontSize: 24, fontWeight: "800" },
  heading: { color: colors.text, fontSize: 17, fontWeight: "700" },
  workspaceSwitcher: {
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 9,
    backgroundColor: colors.panel,
    overflow: "hidden",
  },
  workspaceSwitcherCompact: { flexShrink: 1, minWidth: 0 },
  workspaceSwitcherContent: { flexDirection: "row", padding: 3 },
  workspaceTab: {
    minHeight: 30,
    justifyContent: "center",
    paddingHorizontal: 11,
    borderRadius: 6,
  },
  workspaceTabCompact: { paddingHorizontal: 5 },
  workspaceTabActive: { backgroundColor: colors.greenDark },
  workspaceTabText: { color: "#dfe8df", fontSize: 11, fontWeight: "700" },
  workspaceTabTextCompact: { fontSize: 9 },
  statusCluster: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 10 },
  pill: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 999,
  },
  pillReady: { borderColor: "#356344", backgroundColor: colors.greenDark },
  pillFaulted: { borderColor: "#70413d", backgroundColor: "#321d1b" },
  pillText: { color: colors.muted, fontSize: 12 },
  applianceStatusCard: {
    marginHorizontal: 28,
    marginTop: 14,
    padding: 14,
    gap: 9,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: colors.panel,
  },
  applianceStatusCardCompact: {
    marginHorizontal: 12,
    marginTop: 8,
    padding: 8,
    gap: 7,
  },
  applianceStatusHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  applianceStatusHeadingCompact: { alignItems: "center", flexWrap: "nowrap", gap: 8 },
  applianceStatusIdentity: { flex: 1, minWidth: 0 },
  applianceStatusIdentityCompact: { justifyContent: "center" },
  applianceStatusBoard: {
    color: colors.text,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  applianceStatusBoardCompact: { fontSize: 13 },
  applianceStatusConnection: { marginTop: 4, color: colors.muted, fontSize: 12 },
  applianceStatusConnectionCompact: { marginTop: 1, fontSize: 11 },
  applianceStatusConnectionReady: { color: colors.green },
  applianceStatusConnectionFaulted: { color: colors.red },
  applianceStatusActions: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    flexShrink: 1,
    justifyContent: "flex-end",
    gap: 7,
  },
  applianceStatusActionsCompact: { flexWrap: "nowrap", flexShrink: 0, gap: 5 },
  statusDetailsButton: {
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 999,
  },
  statusDetailsButtonCompact: { minHeight: 34, paddingHorizontal: 8, paddingVertical: 3 },
  statusDetailsButtonText: { color: "#dfe8df", fontSize: 11, fontWeight: "700" },
  applianceActivity: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 7 },
  applianceActivityItem: { color: colors.text, fontSize: 12, fontWeight: "600" },
  applianceActivitySeparator: { color: colors.muted, fontSize: 12 },
  applianceDestination: {
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: 8,
  },
  applianceDestinationLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  applianceDestinationValue: {
    flexShrink: 1,
    color: colors.text,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 11,
    lineHeight: 16,
  },
  applianceStatusDetails: {
    paddingTop: 10,
    gap: 8,
    borderTopColor: colors.line,
    borderTopWidth: 1,
  },
  statusUtilityActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  profileManagerSafeArea: { flex: 1, backgroundColor: colors.background },
  profileManagerHeading: {
    minHeight: 76,
    paddingLeft: 22,
    paddingRight: 132,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
  },
  profileManagerHeadingCopy: { flex: 1, minWidth: 0 },
  profileManagerTitle: { color: colors.text, fontSize: 21, fontWeight: "800" },
  profileManagerScroller: { flex: 1, minHeight: 0 },
  profileManagerContent: {
    width: "100%",
    maxWidth: 720,
    alignSelf: "center",
    padding: 20,
    paddingBottom: 44,
    gap: 16,
  },
  profileOperation: {
    minHeight: 48,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 9,
    backgroundColor: colors.panel2,
  },
  profileOperationError: { borderColor: "#70413d", backgroundColor: "#321d1b" },
  profileOperationSuccess: { borderColor: "#356344", backgroundColor: colors.greenDark },
  profileOperationText: { flex: 1, color: colors.muted, lineHeight: 19 },
  profileOperationErrorText: { color: colors.red },
  profileList: { gap: 10 },
  profileRow: {
    minHeight: 92,
    padding: 14,
    gap: 5,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 11,
    backgroundColor: colors.panel,
  },
  profileRowActive: { borderColor: "#4c8d5b", backgroundColor: colors.greenDark },
  profileRowUnavailable: { opacity: 0.62 },
  profileRowHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  profileBoardLabel: {
    flexShrink: 1,
    color: colors.text,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 16,
    fontWeight: "700",
  },
  profileBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    overflow: "hidden",
    color: colors.muted,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.8,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 999,
  },
  profileBadgeActive: { color: colors.green, borderColor: "#4c8d5b" },
  profileGeneration: { color: colors.muted, fontSize: 11 },
  profileRowActions: {
    marginTop: 7,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  profileConfirmation: {
    padding: 16,
    gap: 10,
    borderColor: "#4c8d5b",
    borderWidth: 1,
    borderRadius: 11,
    backgroundColor: colors.panel2,
  },
  profileConfirmationTitle: { color: colors.text, fontSize: 15, fontWeight: "700" },
  profileAddSection: {
    paddingTop: 16,
    gap: 9,
    borderTopColor: colors.line,
    borderTopWidth: 1,
  },
  button: {
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 8,
    borderColor: "#5b9c69",
    borderWidth: 1,
    backgroundColor: colors.green,
  },
  buttonPressed: { opacity: 0.8 },
  buttonDisabled: { opacity: 0.4 },
  buttonSecondary: { borderColor: colors.line, backgroundColor: "transparent" },
  buttonText: { color: "#0d1b11", fontWeight: "700", textAlign: "center" },
  buttonSecondaryText: { color: "#dfe8df" },
  notificationPermissionBanner: {
    marginHorizontal: 28,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderColor: "#4c8d5b",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.greenDark,
  },
  notificationPermissionText: { flex: 1, color: colors.text, fontSize: 12 },
  errorBanner: {
    marginHorizontal: 28,
    marginTop: 14,
    padding: 12,
    borderColor: "#70413d",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: "#321d1b",
  },
  errorText: { color: colors.red },
  profileOperationBanner: {
    marginHorizontal: 28,
    marginTop: 14,
    padding: 12,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.panel2,
  },
  reconnectBanner: {
    marginHorizontal: 28,
    marginTop: 14,
    padding: 12,
    borderColor: "#356344",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.greenDark,
  },
  reconnectText: { color: colors.muted },
  inlineError: { color: colors.red, fontSize: 12 },
  activity: { position: "absolute", top: 92, right: 16, zIndex: 2 },
  onboardingScroller: { flex: 1, minHeight: 0 },
  onboardingScrollContent: { paddingBottom: 32 },
  onboarding: {
    width: "92%",
    maxWidth: 620,
    alignSelf: "center",
    marginTop: 48,
    padding: 24,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 14,
    backgroundColor: colors.panel,
  },
  onboardingTitle: { marginBottom: 12, color: colors.text, fontSize: 22, fontWeight: "700" },
  secondaryText: { color: colors.muted, lineHeight: 22 },
  bleDiscovery: {
    marginVertical: 20,
    paddingVertical: 16,
    gap: 10,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
  },
  bleDiscoveryTitle: { color: colors.text, fontSize: 16, fontWeight: "700" },
  bleCandidateScroller: { maxHeight: 220 },
  bleCandidateList: { gap: 7 },
  bleCandidate: {
    gap: 4,
    padding: 10,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.panel2,
  },
  bleCandidateSelected: { borderColor: "#5b9c69", backgroundColor: colors.greenDark },
  bleCandidateHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  bleCandidateName: { flex: 1, color: "#dfe8df", fontWeight: "700" },
  bleCandidateChoice: { color: colors.green, fontSize: 11, fontWeight: "700" },
  bleSelectionStatus: { color: colors.green, fontSize: 11, lineHeight: 16 },
  serialRow: {
    marginVertical: 20,
    paddingVertical: 13,
    gap: 8,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
  },
  actionRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 10 },
  shell: { flex: 1, flexDirection: "row", minHeight: 0 },
  shellCompact: { flexDirection: "column" },
  sidebar: {
    width: 320,
    maxWidth: "100%",
    padding: 22,
    borderRightColor: colors.line,
    borderRightWidth: 1,
    backgroundColor: colors.panel,
  },
  sidebarDrawerBackdrop: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#00000099",
  },
  sidebarDrawerDismiss: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  sidebarDrawer: {
    width: "88%",
    maxWidth: 420,
    height: "100%",
    borderRightColor: colors.line,
    borderRightWidth: 1,
    backgroundColor: colors.panel,
  },
  sidebarDrawerHeading: {
    minHeight: 64,
    paddingHorizontal: 18,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
  },
  sidebarCompactScroller: { flex: 1, minHeight: 0 },
  sidebarCompactContent: { padding: 18, paddingBottom: 36 },
  sectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  addButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 17,
  },
  addButtonText: { color: colors.text, fontSize: 22 },
  smallButton: {
    minHeight: 32,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 999,
  },
  smallButtonActive: { borderColor: "#356344", backgroundColor: colors.greenDark },
  smallButtonText: { color: "#dfe8df", fontSize: 11, fontWeight: "700" },
  nearbyPanel: {
    gap: 10,
    marginBottom: 16,
    padding: 12,
    borderColor: "#356344",
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: colors.greenDark,
  },
  nearbyHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  nearbyTitle: { flex: 1, gap: 2 },
  nearbyCaption: { color: colors.muted, fontSize: 10 },
  nearbyStatus: { color: colors.muted, fontSize: 11, lineHeight: 16 },
  nearbyError: { gap: 3 },
  nearbyInterfaces: {
    gap: 6,
    padding: 8,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.panel,
  },
  nearbyInterfaceRow: { gap: 1 },
  nearbyInterfaceName: { color: "#dfe8df", fontSize: 11, fontWeight: "700" },
  nearbyScroller: { maxHeight: 230 },
  nearbyList: { gap: 7 },
  nearbyPeer: {
    gap: 4,
    padding: 10,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.panel,
  },
  nearbyPeerAdded: { borderColor: "#5b9c69" },
  nearbyPeerHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  nearbyPeerName: { flex: 1, color: "#dfe8df", fontWeight: "700" },
  nearbyPeerButtons: { flexDirection: "row", alignItems: "center", gap: 5 },
  nearbyPeerButton: {
    minHeight: 28,
    justifyContent: "center",
    paddingHorizontal: 8,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 999,
  },
  nearbyPeerAction: { color: colors.green, fontSize: 11, fontWeight: "700" },
  contactForm: {
    gap: 9,
    marginBottom: 18,
    padding: 14,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: colors.panel2,
  },
  label: { color: colors.muted, fontSize: 12 },
  input: {
    width: "100%",
    minHeight: 42,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    color: "#f3f7f2",
    backgroundColor: "#0d110e",
  },
  inputReadOnly: { color: colors.muted },
  monospaceInput: {
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  contacts: { gap: 6 },
  contact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderColor: "transparent",
    borderWidth: 1,
    borderRadius: 8,
  },
  contactSelection: { flex: 1, minWidth: 0, gap: 3, padding: 11 },
  contactActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginRight: 8,
  },
  contactActive: { borderColor: colors.line, backgroundColor: colors.panel2 },
  contactPressed: { opacity: 0.8 },
  contactName: { color: "#dfe8df", fontWeight: "700" },
  messageRequestsSection: {
    gap: 7,
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
  },
  messageRequestPreview: { color: colors.muted, fontSize: 11 },
  monospace: {
    color: colors.muted,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 11,
    lineHeight: 16,
  },
  metaRow: { flexDirection: "row", gap: 10 },
  metaLabel: {
    width: 78,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  metaValue: { flex: 1, color: colors.text, fontSize: 12 },
  emptyState: { flex: 1, alignItems: "center", justifyContent: "center", padding: 32 },
  emptyTitle: { marginBottom: 8, color: colors.text, fontSize: 17, fontWeight: "600" },
  conversation: { flex: 1, minWidth: 0 },
  conversationCompact: { minHeight: 0 },
  conversationHeading: {
    minHeight: 72,
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 22,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
  },
  conversationHeadingCompact: { minHeight: 48, paddingLeft: 14, paddingRight: 124 },
  conversationIdentity: { gap: 3 },
  messageRequestBadge: { color: colors.green, fontSize: 9, fontWeight: "800", letterSpacing: 0.7 },
  measurePathButton: {
    position: "absolute",
    top: 12,
    right: 14,
    minHeight: 30,
    justifyContent: "center",
    paddingHorizontal: 9,
    borderColor: "#4c8d5b",
    borderWidth: 1,
    borderRadius: 8,
  },
  measurePathButtonText: { color: colors.green, fontSize: 10, fontWeight: "800" },
  probeResult: {
    gap: 3,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    backgroundColor: colors.greenDark,
  },
  probeResultTitle: { color: colors.text, fontSize: 11, fontWeight: "700" },
  probeResultValue: { color: colors.green, fontSize: 11, fontWeight: "700" },
  probeResultHelp: { color: colors.muted, fontSize: 9, lineHeight: 13 },
  probeResultAction: {
    alignSelf: "flex-start",
    marginTop: 3,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderColor: "#4c8d5b",
    borderWidth: 1,
    borderRadius: 6,
  },
  probeResultActionText: { color: colors.green, fontSize: 9, fontWeight: "800" },
  timelineScroller: { flex: 1 },
  timeline: { flexGrow: 1, gap: 12, padding: 22, justifyContent: "flex-end" },
  timelineCompact: { gap: 9, padding: 12 },
  message: {
    maxWidth: "78%",
    padding: 13,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 12,
  },
  messageInbound: { alignSelf: "flex-start", backgroundColor: colors.panel2 },
  messageOutbound: {
    alignSelf: "flex-end",
    borderColor: "#356344",
    backgroundColor: colors.greenDark,
  },
  messageHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  messageTitle: { flex: 1, marginBottom: 5, color: colors.text, fontWeight: "700" },
  localAcceptanceBadge: {
    color: colors.green,
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  messageActionsButton: {
    minWidth: 28,
    minHeight: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
  },
  messageActionsButtonText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
  },
  messageContent: { color: colors.text, lineHeight: 21 },
  messageLocationChip: {
    marginTop: 9,
    paddingHorizontal: 9,
    paddingVertical: 7,
    gap: 2,
    borderColor: "#506b88",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: "#15212b",
  },
  messageLocationChipLabel: {
    color: "#9ac9f4",
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.9,
  },
  messageLocationChipText: { color: "#c9def0", fontSize: 9, lineHeight: 13 },
  messageFooter: { marginTop: 8, color: colors.muted, fontSize: 10 },
  nomadScroller: { flex: 1 },
  nomadContent: { flexGrow: 1, padding: 22 },
  nomadCard: {
    width: "100%",
    maxWidth: 860,
    alignSelf: "center",
    gap: 10,
    padding: 22,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 14,
    backgroundColor: colors.panel,
  },
  nomadHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 6,
  },
  nomadHeadingCopy: { gap: 2 },
  nomadHint: { flexShrink: 1, color: colors.muted, fontSize: 11, lineHeight: 17 },
  nomadFetchRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 4,
  },
  nomadFetchMeta: {
    gap: 5,
    padding: 11,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.panel2,
  },
  nomadStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 8,
    padding: 14,
    borderColor: "#356344",
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: colors.greenDark,
  },
  nomadStatusCopy: { flex: 1, gap: 3 },
  nomadResult: {
    gap: 10,
    marginTop: 8,
    padding: 14,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: colors.panel2,
  },
  nomadResultTitle: { color: colors.text, fontSize: 15, fontWeight: "700" },
  nomadRawPage: {
    padding: 14,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: "#0d110e",
  },
  nomadRawText: {
    color: colors.text,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 13,
    lineHeight: 20,
  },
  composeScroller: {
    flexGrow: 0,
    flexShrink: 1,
    minHeight: 0,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    backgroundColor: colors.panel,
  },
  composeScrollerCompact: { maxHeight: "60%" },
  compose: { gap: 10, padding: 16 },
  composeCompact: { gap: 6, padding: 9 },
  messageInput: { minHeight: 78, textAlignVertical: "top" },
  messageInputCompact: { minHeight: 48, maxHeight: 96 },
  composerLocationToggle: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 9,
    borderColor: "#506b88",
    borderWidth: 1,
    borderRadius: 9,
    backgroundColor: "#151e27",
  },
  composerLocationToggleCompact: { alignItems: "center", padding: 7 },
  composerLocationCopy: { flex: 1, minWidth: 0, gap: 2 },
  composerLocationCopyCompact: { flexDirection: "row", alignItems: "center", gap: 7 },
  composerLocationTitle: { color: "#b5d9fa", fontSize: 10, fontWeight: "800" },
  composerLocationHelp: { color: colors.muted, fontSize: 9, lineHeight: 13 },
  composerLocationCaveat: { color: "#829bb1", fontSize: 8, lineHeight: 12 },
  composeFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  composerBudget: { flex: 1, minWidth: 0, gap: 2 },
  counter: { color: colors.muted, fontSize: 10 },
  composerBudgetHelp: { color: "#748078", fontSize: 8, lineHeight: 12 },
  counterOverLimit: { color: colors.red },
  messageActionsBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: "#00000099",
  },
  messageActionsDismiss: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  messageActionsSheet: {
    width: "100%",
    maxWidth: 680,
    maxHeight: "88%",
    borderTopColor: colors.line,
    borderTopWidth: 1,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    backgroundColor: colors.panel,
  },
  messageActionsHeading: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
  },
  messageActionsHeadingCopy: { flex: 1, minWidth: 0 },
  messageActionsContent: { padding: 18, paddingBottom: 30, gap: 12 },
  messageRadioDetails: {
    gap: 5,
    paddingTop: 12,
    borderTopColor: colors.line,
    borderTopWidth: 1,
  },
  messageAttachedLocationDetails: {
    gap: 7,
    padding: 11,
    borderColor: "#506b88",
    borderWidth: 1,
    borderRadius: 9,
    backgroundColor: "#151e27",
  },
  messageActivityDetails: {
    gap: 8,
    paddingTop: 12,
    borderTopColor: colors.line,
    borderTopWidth: 1,
  },
  messageTraceActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  messageActionUtilities: {
    gap: 10,
    paddingTop: 12,
    borderTopColor: colors.line,
    borderTopWidth: 1,
  },
  messageSendAgainNotice: { gap: 10 },
});
