// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "reticulum-appliance-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "ReticulumApplianceNativeSpec.h"

@interface ApplianceNative : NSObject <NativeApplianceNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ApplianceNative : NSObject <RCTBridgeModule>
#endif

@end