import type { BytesView } from "../generated/api.ts";

/** Present a generated byte field without guessing that binary data is UTF-8. */
export function bytesText(field: BytesView): string {
  return field.encoding === "utf8" ? field.value : `hex:${field.value}`;
}
