// Generated by uniffi-bindgen-react-native
#include "reticulum-appliance-native.h"
#include "generated/reticulum_appliance_native.hpp"

namespace reticulum_appliancenative {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeReticulumApplianceNative::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}