[package]
name = "reticulum-tx-supervisor"
description = "Transport-neutral Reticulum node and interface supervisor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []

[dependencies]
embassy-sync.workspace = true
rand_core.workspace = true
reticulum-interface-router = { path = "../interface-router", default-features = false }
reticulum-node-core = { path = "../node-core", default-features = false }
reticulum-tx-handoff = { path = "../tx-handoff", default-features = false }

[dev-dependencies]
reticulum-rns-rete = { path = "../rns-rete", default-features = false }

[lib]
path = "src/lib.rs"
