// Generated by uniffi-bindgen-react-native
package org.reticulum.appliance.nativebridge

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder

@ReactModule(name = ApplianceNativeModule.NAME)
class ApplianceNativeModule(reactContext: ReactApplicationContext) :
  NativeApplianceNativeSpec(reactContext) {

  // Product-owned platform half of PRNS's Android Bluetooth Auto interface.
  private val prnsBluetoothAuto = PrnsBluetoothAuto(reactContext.applicationContext)

  override fun getName(): String {
    return NAME
  }

  // Two native methods implemented in cpp-adapter.cpp, and ultimately
  // reticulum-appliance-native.cpp

  external fun nativeInstallRustCrate(runtimePointer: Long, callInvoker: CallInvokerHolder): Boolean
  external fun nativeCleanupRustCrate(runtimePointer: Long): Boolean

  override fun installRustCrate(): Boolean {
    val context = this.reactApplicationContext
    val installed = nativeInstallRustCrate(
      context.javaScriptContextHolder!!.get(),
      context.jsCallInvokerHolder!!
    )
    if (installed) {
      prnsBluetoothAuto.start()
    }
    return installed
  }

  override fun cleanupRustCrate(): Boolean {
    prnsBluetoothAuto.stop()
    return nativeCleanupRustCrate(
      this.reactApplicationContext.javaScriptContextHolder!!.get()
    )
  }

  override fun invalidate() {
    prnsBluetoothAuto.stop()
    super.invalidate()
  }

  companion object {
    const val NAME = "ApplianceNative"

    init {
      System.loadLibrary("reticulum-appliance-native")
    }
  }
}