schema = 1

[reticulum.released]
version = "1.4.2"
repository = "https://github.com/markqvist/Reticulum.git"
revision = "b48b96e61676504e0a4e527b33b9a0b4495c6872"

[implementations.prns]
version = "0.3.6"
repository = "https://github.com/evelant/Prns.git"
revision = "b763fb5076a965d6eb411923c387e3805f47e40a"
upstream_repository = "https://github.com/KenAKAFrosty/Prns.git"
upstream_revision = "f7872d6fcad9c5ba33b942bc19bb183f2b4a0d13"
